version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - /data/postgres:/data/postgres
    ports:
      - "5400:5432"
    restart: unless-stopped
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      RACK_ENV: development
  pgadmin:
      image: fenglc/pgadmin4
      environment:
        DEFAULT_USER: your_email@example.com
        DEFAULT_PASSWORD: 123456789
      volumes:
         - /data/pgadmin:/root/.pgadmin
      ports:
        - "5050:5050"
      restart: unless-stopped
      depends_on:
        - db
